### ISSUE TITLE
Calling `context` when not set segfaults

### ISSUE THREAD

**Issue by SpacePossum** [hjr3/pecl-gearman#15]
```php
$client = new \GearmanClient();
$client->context();
```

```bash
Segmentation fault (core dumped)
```

```bash
$ php -v
PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

```php
<?php var_dump(phpversion('gearman'));
// "2.0.0-dev"
```

**Comment by SpacePossum** [comment]
Btw. also:
```php
        $client = new \GearmanClient();
        $client->setContext('_test_');
        var_dump($client->context());
        die;
```

```
string(8) "_test_\000\000"
```

which is not expected

**Comment by SpacePossum** [comment]
any interest?

**Comment by hjr3** [comment]
@SpacePossum i saw this issue via mail and mistakenly thought it was part of the thread for php7 support. I asked in that thread if anyone has created. We do not have an official PHP7 release yet.

**Comment by SpacePossum** [comment]
I'll close this one for now than and test when there is a RC for PHP7.
Thanks for the feedback! :)

**Comment by wcgallego** [comment]
@SpacePossum Current version is 2.0.1 on my branch (https://github.com/wcgallego/pecl-gearman).

Can you give that a shot?

**Comment by SpacePossum** [comment]
sorry for the late response, and the screenshot (select-copy seems to be disabled, I'll report that to Ubuntu ;))

**Comment by wcgallego** [comment]
Ah, makes sense. I think I see the problem.

Reopening, but look for the fix on my repo, @SpacePossum

**Comment by SpacePossum** [comment]
thanks and will do :)
let me know if I can help out, I haven't done much of C programming of PHP extensions lately but happy to pick it up again

**Comment by wcgallego** [comment]
@SpacePossum Should be fixed there, both on master and the 2.0.1 tag. Your test script and the test suite (aside from an integration test that was failing before) looking like they're working.

Can you let me know?

**Comment by SpacePossum** [comment]
```php
<?php

$client = new \GearmanClient();
$a = $client->context();
var_dump($a);
$client->setContext('_test_');
$a = $client->context();
var_dump($a);
```

```bash
$ php -v
PHP 7.0.10-2+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10-2+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

Now works as a charm now :)
Thanks @wcgallego !

**Comment by wcgallego** [comment]
👍
